language: ruby
jdk: oraclejdk7
notifications:
  email:
    - levi@leviwilson.com
script:
  - bundle install
  - rake release_apk
  - ant test
  - bundle exec rake test
before_install:
  - export FLAVORS=platform-tools,build-tools-19.0.1,android-10,android-15,android-19,sysimg-19,extra-android-support
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/19.0.1
  - echo y | android update sdk --filter ${FLAVORS} --no-ui --force
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
